// <auto-generated />
namespace ImportAndPreviewApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddingEmployeeNameandEmployeeCodeinformationinReportDataEntitytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingEmployeeNameandEmployeeCodeinformationinReportDataEntitytable));
        
        string IMigrationMetadata.Id
        {
            get { return "201803300949411_Adding EmployeeName and EmployeeCode information in ReportDataEntity table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
